/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _MDATA_H_RPCGEN
#define _MDATA_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct manageData {
	int type;
	int value;
	int time;
};
typedef struct manageData manageData;

struct computeData {
	int type;
	int start;
	int end;
};
typedef struct computeData computeData;

struct range_entry {
	int start;
	int end;
};
typedef struct range_entry range_entry;

struct reportData {
	char hostName[20];
	int fd;
	int perfArray[6];
	int perfIndex;
	int numTested;
	int numRange;
	int offset;
	range_entry rangeArray[1000];
};
typedef struct reportData reportData;

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_manageData (XDR *, manageData*);
extern  bool_t xdr_computeData (XDR *, computeData*);
extern  bool_t xdr_range_entry (XDR *, range_entry*);
extern  bool_t xdr_reportData (XDR *, reportData*);

#else /* K&R C */
extern bool_t xdr_manageData ();
extern bool_t xdr_computeData ();
extern bool_t xdr_range_entry ();
extern bool_t xdr_reportData ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_MDATA_H_RPCGEN */
