/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "mdata.h"

bool_t
xdr_manageData (XDR *xdrs, manageData *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->type))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->value))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->time))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_computeData (XDR *xdrs, computeData *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->type))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->start))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->end))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_range_entry (XDR *xdrs, range_entry *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->start))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->end))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_reportData (XDR *xdrs, reportData *objp)
{
	register int32_t *buf;

	int i;

	if (xdrs->x_op == XDR_ENCODE) {
		 if (!xdr_vector (xdrs, (char *)objp->hostName, 20,
			sizeof (char), (xdrproc_t) xdr_char))
			 return FALSE;
		buf = XDR_INLINE (xdrs, (5 + ( 6 )) * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->fd))
				 return FALSE;
			 if (!xdr_vector (xdrs, (char *)objp->perfArray, 6,
				sizeof (int), (xdrproc_t) xdr_int))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->perfIndex))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->numTested))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->numRange))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->offset))
				 return FALSE;

		} else {
		IXDR_PUT_LONG(buf, objp->fd);
		{
			register int *genp;

			for (i = 0, genp = objp->perfArray;
				i < 6; ++i) {
				IXDR_PUT_LONG(buf, *genp++);
			}
		}
		IXDR_PUT_LONG(buf, objp->perfIndex);
		IXDR_PUT_LONG(buf, objp->numTested);
		IXDR_PUT_LONG(buf, objp->numRange);
		IXDR_PUT_LONG(buf, objp->offset);
		}
		 if (!xdr_vector (xdrs, (char *)objp->rangeArray, 1000,
			sizeof (range_entry), (xdrproc_t) xdr_range_entry))
			 return FALSE;
		return TRUE;
	} else if (xdrs->x_op == XDR_DECODE) {
		 if (!xdr_vector (xdrs, (char *)objp->hostName, 20,
			sizeof (char), (xdrproc_t) xdr_char))
			 return FALSE;
		buf = XDR_INLINE (xdrs, (5 + ( 6 )) * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->fd))
				 return FALSE;
			 if (!xdr_vector (xdrs, (char *)objp->perfArray, 6,
				sizeof (int), (xdrproc_t) xdr_int))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->perfIndex))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->numTested))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->numRange))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->offset))
				 return FALSE;

		} else {
		objp->fd = IXDR_GET_LONG(buf);
		{
			register int *genp;

			for (i = 0, genp = objp->perfArray;
				i < 6; ++i) {
				*genp++ = IXDR_GET_LONG(buf);
			}
		}
		objp->perfIndex = IXDR_GET_LONG(buf);
		objp->numTested = IXDR_GET_LONG(buf);
		objp->numRange = IXDR_GET_LONG(buf);
		objp->offset = IXDR_GET_LONG(buf);
		}
		 if (!xdr_vector (xdrs, (char *)objp->rangeArray, 1000,
			sizeof (range_entry), (xdrproc_t) xdr_range_entry))
			 return FALSE;
	 return TRUE;
	}

	 if (!xdr_vector (xdrs, (char *)objp->hostName, 20,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->fd))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->perfArray, 6,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->perfIndex))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->numTested))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->numRange))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->offset))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->rangeArray, 1000,
		sizeof (range_entry), (xdrproc_t) xdr_range_entry))
		 return FALSE;
	return TRUE;
}
